AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firewalla-exporter

Resources:

  FirewallaExporter:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: exporter
      CodeUri: lambda/
      Runtime: provided.al2
      MemorySize: 1024
      Timeout: 30
      Tracing: Active
      ReservedConcurrentExecutions: 1
      Architectures:
      - arm64
      Environment:
        Variables:
          AXIOM_DATASET: 
          AXIOM_TOKEN: 
          AXIOM_ORG_ID: 
          FIREWALLA_KEY: 
          FIREWALLA_URL:
      Policies:
        - AWSLambdaExecute 
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
