AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firewalla-exporter

Resources:

  FirewallaExporter:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: exporter
      CodeUri: lambda/
      Runtime: go1.x
      MemorySize: 1024
      Timeout: 180
      Tracing: Active
      ReservedConcurrentExecutions: 1
      Architectures:
      - x86_64
      Environment:
        Variables:
      Policies:
        - AWSLambdaExecute 
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
